### ISSUE TITLE
[BUG] Cloning tree with hidden pages leads to error

### ISSUE THREAD

**Issue by calien666** [sudhaus7/wizard#1]
**Issue**
When cloning a page tree with hidden pages inside, the method `CreateProcess::cloneTree` doesn't respect hidden pages. Therefor the process stucks in erroring trying to access an array key on false.

**Expected behaviour**
* Either allow cloning of hidden pages
  * refactor `Localdatabase::getRow` getting hidden records, too
* or check, if given page is an array or false

**Comment by foppelfb** [comment]
fixed in commit 884d8625bd28a6492fcfbf626624c9e5c0043633
please test

**Comment by calien666** [comment]
Done
